swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /hello/{name}:
        get:
            tags:
                - hello
            summary: sayHello hello
            operationId: hello#sayHello
            parameters:
                - name: name
                  in: path
                  description: 挨拶する相手の名前
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
